baseURL: http://mikezornek.com
name: Mike Zornek
description: Sharing life and geek notes from Philadelphia.
author: Mike Zornek
title: Mike Zornek
languageCode: "en-us"
theme: "zornek"
params:
  description: Sharing life and geek notes from Philadelphia.
pygmentsCodeFences: true
pygmentsStyle: tango
pygmentsCodefencesGuessSyntax: true
paginate: 20
markup:
  defaultMarkdownHandler: blackfriday
  goldmark:
    extensions:
      typographer: true
    renderer:
      unsafe: true
  blackFriday:
    angledQuotes: false
    extensions: null
    extensionsMask: null
    footnoteAnchorPrefix: ""
    footnoteReturnLinkContents: ""
    fractions: true
    hrefTargetBlank: false
    latexDashes: true
    nofollowLinks: false
    noreferrerLinks: false
    plainIDAnchors: true
    skipHTML: false
    smartDashes: true
    smartypants: true
    smartypantsQuotesNBSP: false
    taskLists: true
menu:
  main:
    - name: Home
      url: /
      weight: 10
    - name: Blog
      url: /posts/
      weight: 20
    - name: Projects
      url: /projects/
      weight: 30
    - name: For Hire
      url: /for-hire/
      weight: 40
    - name: Values
      url: /values/
      weight: 50
    - name: Follow
      url: /follow/
      weight: 55
    - name: Contact
      url: /contact/
      weight: 60
